// const mongoose = require("mongoose");
// const Schema = mongoose.Schema;

// const ContactsSchema = new Schema({
//   client: {
//     type: String,
//     // required: true,
//   },
//   campaign: {
//     type: String,
//     // required: true,
//   },
//   first_name: {
//     type: String,
//     // required: true,
//   },
//   email: {
//     type: String,
//     // required: true,
//   },
//   company: String,
//   company_name: {
//     type: String,
//     // required: true,
//   },
//   title: String,

//   website: {
//     type: String,
//     // required: true,
//   },
//   annual_revenue: String,
//   category:String,
//   cfo:String,
//   company_city: String,
//   company_address: String,
//   company_country: String,
//   country:String,
//   company_linked_in: String,
//   company_linkedin_url: String,
//   company_facebook:String,
//   company_name_for_emails:String,
//   current_sequence_number:String,
//   custom_sequence_sentence:String,
//   custom_outreach_plan:String,
//   compnay_phone:String,
//   company_state: String,
//   departments:String,
//   email_confidence: String,
//   email_status:String,
//   empolyess:String,
//   facebook_url:String,
//   first_phone: String,
//   free:String,
//   industry:String,
//   keywords: String,
//   last_name:String,
//   last_raised_at: String,
//   latest_funding: String,
//   latest_funding_amount: String,
//   person_linkedin_url: String,
//   quality: String,
//   result: String,
//   role: String,
//   seniority:String,
//   seo_description: String,
//   org_number:String,
//   chip_check:String,
//   state:String,
//   technologies: String,
//   title: String,
//   total_funding: String,
//   twitter_url: String,
//   comment_on_content_piece:String,
//   market:String,
//   news:String,
//   notable_details:String,
//   specific_industry:String,
//   spoken_industry:String,
//   target_audience:String,
//   simplified_title:String,
//   simplified_name:String,
//   value_proposition:String,
//   simplified_company_name:String,
//   simplified_company_name_proper:String,
//   location:String,
//   title_for_emails:String,
//   enrichment_status:String,
//   scraping_status:String,
//   date: { type: Date, default: Date.now },
// });

// const ContactsModal = mongoose.model("contacts", ContactsSchema);

// module.exports = ContactsModal;
